### PR TITLE
Add custom replacement option

### LINKED ISSUE #38: Feature request: Custom placeholder support
Please consider support for custom placeholders, which would allow defined values to be used in multiple holograms.

Similar to an existing feature in HD.

### PR DESCRIPTION
**Pull request by Andre601**
This idea was suggested by @SlimeDog in #38 

It essentially adds a way to add your own placeholder text that DH should replace with a replacement value, similar to what HolographicDisplays is offering (i.e. `[x]` for a full block icon).

To be honest: Not THAT happy with the way I implemented it (Not even sure if it actually works like this but I assume the HologramLine is where this would be rendered anyways).
But I hope it works. Any feedback is welcome.

Closes #38

### CODE REVIEW

**Comment by SlimeDog** [comment]
As I mentioned in the Discord, PAPI Shortcut is an adequate replacement for custom placeholders, at least in my usage. For example, I added
```
% cat plugins/PlaceholderAPI/shortcuts/rip_top.txt
 &fREQUIESCAT
% cat plugins/PlaceholderAPI/shortcuts/rip_bottom.txt
 &fIN PACE 
```
Then in the hologram files (converted from HD):
```
location: world_city:-390.500:67.206:60.500
enabled: true
display-range: 48
update-range: 48
update-interval: 20
facing: 0.0
down-origin: false
pages:
- lines:
  - content: '%shortcut_rip_top%'
    height: 0.3
  - content: '%shortcut_rip_bottom%'
    height: 0.3
  actions: {}
```
works just the way it needs to do.

**Comment by SlimeDog** [comment]
As I mentioned in the Discord, PAPI Shortcut is an adequate replacement for custom placeholders, at least in my usage. For example, I added
```
% cat plugins/PlaceholderAPI/shortcuts/rip_top.txt
 &fREQUIESCAT
% cat plugins/PlaceholderAPI/shortcuts/rip_bottom.txt
 &fIN PACE 
```
Then in the hologram files (converted from HD):
```
location: world_city:-390.500:67.206:60.500
enabled: true
display-range: 48
update-range: 48
update-interval: 20
facing: 0.0
down-origin: false
pages:
- lines:
  - content: '%shortcut_rip_top%'
    height: 0.3
  - content: '%shortcut_rip_bottom%'
    height: 0.3
  actions: {}
```
works just the way it needs to do.

**Comment by Andre601** [comment]
> As I mentioned in the Discord, PAPI Shortcut is an adequate replacement for custom placeholders, at least in my usage. For example, I added
> 
> ```
> % cat plugins/PlaceholderAPI/shortcuts/rip_top.txt
>  &fREQUIESCAT
> % cat plugins/PlaceholderAPI/shortcuts/rip_bottom.txt
>  &fIN PACE 
> ```
> 
> Then in the hologram files (converted from HD):
> 
> ```
> location: world_city:-390.500:67.206:60.500
> enabled: true
> display-range: 48
> update-range: 48
> update-interval: 20
> facing: 0.0
> down-origin: false
> pages:
> - lines:
>   - content: '%shortcut_rip_top%'
>     height: 0.3
>   - content: '%shortcut_rip_bottom%'
>     height: 0.3
>   actions: {}
> ```
> 
> works just the way it needs to do.

Why the duplicate comment?

**Comment by SlimeDog** [comment]
> Why the duplicate comment?

So that someone who doesn't follow the links will still see it. Why copy it again?

**Comment by Andre601** [comment]
Not entirely sure if what I implemented works as it should... I really hope tho.

**Pull request merged**
