### PR TITLE
Add support for 1.21 with ICON

### PR DESCRIPTION
**Pull request by resi23**

### CODE REVIEW

**Comment by resi23** [comment]
For Testing
[DecentHolograms-2.8.9.jar.zip](https://github.com/user-attachments/files/15936565/DecentHolograms-2.8.9.jar.zip)

**Comment by BySwiizen** [comment]
It works for me too.

**Comment by resi23** [comment]
With "Fix PLAYER_HEAD in #ICON for 1.21"
[DecentHolograms-2.8.9.jar.zip](https://github.com/user-attachments/files/15983246/DecentHolograms-2.8.9.jar.zip)

**Comment by Wolf2323** [comment]
I wanted to test this, and I have this exception:

```
[15:28:44 INFO]: [NBTAPI] [NBTAPI] Found Minecraft: 1.21! Trying to find NMS support
[15:28:44 WARN]: [NBTAPI] [NBTAPI] This Server-Version(1.21-R0.1-SNAPSHOT) is not supported by this NBT-API Version(2.12.4) located in DecentHolograms. The NBT-API will try to work as good as it can! Some functions may not work!
[15:28:44 INFO]: [NBTAPI] [NBTAPI] Using the plugin 'DecentHolograms' to create a bStats instance!
[15:28:44 ERROR]: Error occurred while enabling BetonQuest v2.1.3-DEV-UNOFFICIAL (Is it up to date?)
java.lang.ExceptionInInitializerError: null
	at DecentHolograms-2.8.9.jar/eu.decentsoftware.holograms.libs.nbtapi.NBTCompound.hasTag(NBTCompound.java:720) ~[DecentHolograms-2.8.9.jar:?]
	at DecentHolograms-2.8.9.jar/eu.decentsoftware.holograms.api.utils.items.HologramItem.fromItemStack(HologramItem.java:181) ~[DecentHolograms-2.8.9.jar:?]
	at DecentHolograms-2.8.9.jar/eu.decentsoftware.holograms.api.DHAPI.setHologramLine(DHAPI.java:704) ~[DecentHolograms-2.8.9.jar:?]
	at BetonQuest.jar/org.betonquest.betonquest.compatibility.holograms.decentholograms.DecentHologramsHologram.setLine(DecentHologramsHologram.java:44) ~[BetonQuest.jar:?]
	at BetonQuest.jar/org.betonquest.betonquest.compatibility.holograms.lines.ItemLine.setLine(ItemLine.java:27) ~[BetonQuest.jar:?]
	at BetonQuest.jar/org.betonquest.betonquest.compatibility.holograms.HologramWrapper.initialiseContent(HologramWrapper.java:115) ~[BetonQuest.jar:?]
	at BetonQuest.jar/org.betonquest.betonquest.compatibility.holograms.HologramRunner.addHologram(HologramRunner.java:60) ~[BetonQuest.jar:?]
	at BetonQuest.jar/org.betonquest.betonquest.compatibility.holograms.HologramLoop.initializeHolograms(HologramLoop.java:135) ~[BetonQuest.jar:?]
	at BetonQuest.jar/org.betonquest.betonquest.compatibility.holograms.HologramLoop.initialize(HologramLoop.java:88) ~[BetonQuest.jar:?]
	at BetonQuest.jar/org.betonquest.betonquest.compatibility.holograms.LocationHologramLoop.<init>(LocationHologramLoop.java:26) ~[BetonQuest.jar:?]
	at BetonQuest.jar/org.betonquest.betonquest.compatibility.holograms.HologramProvider.hook(HologramProvider.java:160) ~[BetonQuest.jar:?]
	at BetonQuest.jar/org.betonquest.betonquest.compatibility.holograms.HologramProvider.init(HologramProvider.java:100) ~[BetonQuest.jar:?]
	at BetonQuest.jar/org.betonquest.betonquest.compatibility.Compatibility.<init>(Compatibility.java:88) ~[BetonQuest.jar:?]
	at BetonQuest.jar/org.betonquest.betonquest.BetonQuest.onEnable(BetonQuest.java:549) ~[BetonQuest.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202) ~[paper-1.21.jar:1.21-9-4ea696f]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.21.jar:1.21-9-4ea696f]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520) ~[paper-api-1.21-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:629) ~[paper-1.21.jar:1.21-9-4ea696f]
	at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:578) ~[paper-1.21.jar:1.21-9-4ea696f]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:690) ~[paper-1.21.jar:1.21-9-4ea696f]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:452) ~[paper-1.21.jar:1.21-9-4ea696f]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) ~[paper-1.21.jar:1.21-9-4ea696f]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-9-4ea696f]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-9-4ea696f]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "Object.hashCode()" because "pk" is null
	at java.base/java.util.ImmutableCollections$MapN.probe(ImmutableCollections.java:1328) ~[?:?]
	at java.base/java.util.ImmutableCollections$MapN.get(ImmutableCollections.java:1242) ~[?:?]
	at java.base/java.util.ImmutableCollections$AbstractImmutableMap.getOrDefault(ImmutableCollections.java:1097) ~[?:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflection.mapDeclaredFieldName(PaperReflection.java:81) ~[paper-1.21.jar:1.21-9-4ea696f]
	at io.papermc.reflectionrewriter.runtime.AbstractDefaultRulesReflectionProxy.getDeclaredField(AbstractDefaultRulesReflectionProxy.java:90) ~[reflection-rewriter-runtime-0.0.1.jar:?]
	at io.papermc.paper.pluginremap.reflect.PaperReflectionHolder.getDeclaredField(Unknown Source) ~[paper-1.21.jar:1.21-9-4ea696f]
	at DecentHolograms-2.8.9.jar/eu.decentsoftware.holograms.libs.nbtapi.NBTReflectionUtil.<clinit>(NBTReflectionUtil.java:59) ~[DecentHolograms-2.8.9.jar:?]
	... 26 more
```

**Comment by Tsoccerguy3** [comment]
https://api.papermc.io/v2/projects/paper/versions/1.21/builds/37/downloads/paper-1.21-37.jar try this paper version

**Comment by resi23** [comment]
And This DH ^^ Sry 
[DecentHolograms-2.8.9.jar.zip](https://github.com/user-attachments/files/15990937/DecentHolograms-2.8.9.jar.zip)

**Comment by Wolf2323** [comment]
yes, this seems to work fine

**Pull request merged**
