### PR TITLE
fix §sepcialCharacter not being supported

### PR DESCRIPTION
**Pull request by iiAhmedYT**
It is tested and seems to be working like this

### CODE REVIEW

**Comment by d0by1** [comment]
Hello, is this issue related to the problem we were discussing on discord regarding color codes not working properly with PlaceholderAPI? There has been a fix for this particular problem in PlaceholderAPI and we should not need this change in DH anymore.

**Comment by GavinGoGaming** [comment]
why..? Minecraft doesnt support that character in chat or anything anymore, and cant be written in vanilla. The & symbol is used as an alternative, more user-friendly way to use color codes.

**Comment by GavinGoGaming** [comment]
Also - with support of minimessage in DH v3, this also wont be needed

**Comment by iiAhmedYT** [comment]
It was a bug long ago no longer needed to be fixed, please stop replying in multiple messages

**Comment by iiAhmedYT** [comment]
> Hello, is this issue related to the problem we were discussing on discord regarding color codes not working properly with PlaceholderAPI? There has been a fix for this particular problem in PlaceholderAPI and we should not need this change in DH anymore.

i wasn't exactly who discussed it on discord w/ you no, but it was a problem for me

**Comment by d0by1** [comment]
Alright, I understand it's no longer needed. I will close this PR then.

**Pull request closed without merging**
