### PR TITLE
update to 1.20.4

### LINKED ISSUE #173: 1.20.4 support
Should be self-explanatory, but it would be nice to have 1.20.4 support.

### PR DESCRIPTION
**Pull request by DaJokni**
closes #173

### CODE REVIEW

**Comment by resi23** [comment]
Thanks, works for me

**Comment by fszf** [comment]
> Thanks, works for me
> closes #173
Can either of you help me build this?  I cloned this fork and loaded it into intellij and built the jar.  It was in build\libs\DecentHolograms-2.8.5.jar
My jar output is 402kb
Loading it on my 1.20.4 purpur server I'm getting an error which I think is because of my bad build.  Any suggestions or a link to your binary is very much appreciated.


ERROR19:46:46
Error occurred while enabling DecentHolograms v2.8.5 (Is it up to date?)
Console19:46:46
java.lang.IllegalStateException: DecentHolograms is not running (yet). Do you have DecentHolograms plugin installed?
at eu.decentsoftware.holograms.api.DecentHologramsAPI.get(DecentHologramsAPI.java:97) ~[DecentHolograms-2.8.5.jar:?]
at eu.decentsoftware.holograms.plugin.DecentHologramsPlugin.onEnable(DecentHologramsPlugin.java:25) ~[DecentHolograms-2.8.5.jar:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[purpur-1.20.4.jar:git-Purpur-2105]
at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.4.jar:git-Purpur-2105]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.4-R0.1-SNAPSHOT.jar:?]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:651) ~[purpur-1.20.4.jar:git-Purpur-2105]
at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:562) ~[purpur-1.20.4.jar:git-Purpur-2105]
at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:676) ~[purpur-1.20.4.jar:git-Purpur-2105]
at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:436) ~[purpur-1.20.4.jar:git-Purpur-2105]
at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:342) ~[purpur-1.20.4.jar:git-Purpur-2105]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1146) ~[purpur-1.20.4.jar:git-Purpur-2105]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:324) ~[purpur-1.20.4.jar:git-Purpur-2105]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by resi23** [comment]
Try this 

https://github.com/resi23/DecentHolograms/releases/tag/2.8.6

**Comment by fszf** [comment]
> Try this
> 
> https://github.com/resi23/DecentHolograms/releases/tag/2.8.6

Thank you sir.  Loads perfectly for me now.  Thank you for sharing.

**Pull request merged**
